services:
  - type: web
    name: taxapp-backend
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend/main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
    plan: free
    autoDeploy: true

  - type: web
    name: taxapp-frontend
    env: static
    rootDir: .
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
    plan: free
