services:
  - type: web
    name: taxapp-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false  # You'll set this manually in Render dashboard
    plan: free
    autoDeploy: true
    region: oregon
    repo: keshavcpa01/TaxApp
    branch: main
    rootDir: .  # Keep root, app lives in `backend/`

  - type: web
    name: taxapp-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    plan: free
    autoDeploy: true
    region: oregon
    repo: keshavcpa01/TaxApp
    branch: main
    rootDir: .
